# Generated by Django 4.1.7 on 2023-03-28 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='files/')),
                ('create_date', models.DateField(default=datetime.datetime(2023, 3, 28, 11, 42, 48, 449926, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
