# Generated by Django 4.2 on 2023-04-10 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='create_date',
        ),
        migrations.AddField(
            model_name='quiz',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2023, 4, 10, 21, 55, 10, 230703, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.TextField(default='Викторина', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
